services:
  - type: web
    name: samarth-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
